
/*
	File Generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file CategorySalesFor1997Test.cs instead.
*/
#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using Northwind.Entities;
using Northwind.Data;

#endregion

namespace Northwind.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="CategorySalesFor1997"/> objects (entity, collection and repository).
    /// </summary>
    public partial class CategorySalesFor1997Test
    {
    	// the CategorySalesFor1997 instance used to test the repository.
		private CategorySalesFor1997 mock;
		
		// the VList<CategorySalesFor1997> instance used to test the repository.
		private VList<CategorySalesFor1997> mockCollection;		

        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>
        static private void Init_Generated()
        {
			System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the CategorySalesFor1997 Entity with the {0} --", Northwind.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
        static private void CleanUp_Generated()
        {       	
			System.Console.WriteLine();
			System.Console.WriteLine();
        }
		
		/// <summary>
		/// Selects a page of CategorySalesFor1997 objects from the database.
		/// </summary>
		private void Step_1_SelectAll_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.CategorySalesFor1997Provider.GetPaged(null, 0, 10, out count);
			Assert.IsTrue(count >= 0, "Select Query Failed with GetPaged");
			System.Console.WriteLine("DataRepository.CategorySalesFor1997Provider.GetPaged():");			
			System.Console.WriteLine(mockCollection);			
		}
		
		/// <summary>
		/// Searches some CategorySalesFor1997 objects from the database.
		/// </summary>
		private void Step_2_Search_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.CategorySalesFor1997Provider.Find(null, null, "", 0, 10, out count);
			Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
			
			System.Console.WriteLine("DataRepository.CategorySalesFor1997Provider.Find():");			
			System.Console.WriteLine(mockCollection);
					
		}
		 //Find
			
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock CategorySalesFor1997 entity into a temporary file.
		/// </summary>
		private void Step_6_SerializeEntity_Generated()
		{
			string fileName = "temp_CategorySalesFor1997.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(CategorySalesFor1997)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mock); 
			myWriter.Close();
			System.Console.WriteLine("mock correctly serialized to a temporary file.");			
		}
		
		/// <summary>
		/// Deserialize the mock CategorySalesFor1997 entity from a temporary file.
		/// </summary>
		private void Step_7_DeserializeEntity_Generated()
		{
			string fileName = "temp_CategorySalesFor1997.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(CategorySalesFor1997)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			mock = (CategorySalesFor1997) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a CategorySalesFor1997 collection into a temporary file.
		/// </summary>
		private void Step_8_SerializeCollection_Generated()
		{
			string fileName = "temp_CategorySalesFor1997Collection.xml";
		
			VList<CategorySalesFor1997> mockCollection = new VList<CategorySalesFor1997>();
			mockCollection.Add(mock);
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<CategorySalesFor1997>)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mockCollection); 
			myWriter.Close();
			
			System.Console.WriteLine("VList<CategorySalesFor1997> correctly serialized to a temporary file.");					
		}
		
		
		/// <summary>
		/// Deserialize a CategorySalesFor1997 collection from a temporary file.
		/// </summary>
		private void Step_9_DeserializeCollection_Generated()
		{
			string fileName = "temp_CategorySalesFor1997Collection.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<CategorySalesFor1997>)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			VList<CategorySalesFor1997> mockCollection = (VList<CategorySalesFor1997>) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("VList<CategorySalesFor1997> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		#region Mock Instance
		///<summary>
		///  Returns a Typed CategorySalesFor1997 Entity with mock values.
		///</summary>
		static public CategorySalesFor1997 CreateMockInstance()
		{		
			CategorySalesFor1997 mock = new CategorySalesFor1997();
						
			mock.CategoryName = TestUtility.Instance.RandomString(6, false);;
			mock.CategorySales = TestUtility.Instance.RandomShort();
		   return (CategorySalesFor1997)mock;
		}
		

		#endregion
    }
}
