
/*
	File Generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file InvoicesTest.cs instead.
*/
#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using Northwind.Entities;
using Northwind.Data;

#endregion

namespace Northwind.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="Invoices"/> objects (entity, collection and repository).
    /// </summary>
    public partial class InvoicesTest
    {
    	// the Invoices instance used to test the repository.
		private Invoices mock;
		
		// the VList<Invoices> instance used to test the repository.
		private VList<Invoices> mockCollection;		

        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>
        static private void Init_Generated()
        {
			System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the Invoices Entity with the {0} --", Northwind.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
        static private void CleanUp_Generated()
        {       	
			System.Console.WriteLine();
			System.Console.WriteLine();
        }
		
		/// <summary>
		/// Selects a page of Invoices objects from the database.
		/// </summary>
		private void Step_1_SelectAll_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.InvoicesProvider.GetPaged(null, 0, 10, out count);
			Assert.IsTrue(count >= 0, "Select Query Failed with GetPaged");
			System.Console.WriteLine("DataRepository.InvoicesProvider.GetPaged():");			
			System.Console.WriteLine(mockCollection);			
		}
		
		/// <summary>
		/// Searches some Invoices objects from the database.
		/// </summary>
		private void Step_2_Search_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.InvoicesProvider.Find(null, null, "", 0, 10, out count);
			Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
			
			System.Console.WriteLine("DataRepository.InvoicesProvider.Find():");			
			System.Console.WriteLine(mockCollection);
					
		}
		 //Find
			
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock Invoices entity into a temporary file.
		/// </summary>
		private void Step_6_SerializeEntity_Generated()
		{
			string fileName = "temp_Invoices.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(Invoices)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mock); 
			myWriter.Close();
			System.Console.WriteLine("mock correctly serialized to a temporary file.");			
		}
		
		/// <summary>
		/// Deserialize the mock Invoices entity from a temporary file.
		/// </summary>
		private void Step_7_DeserializeEntity_Generated()
		{
			string fileName = "temp_Invoices.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(Invoices)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			mock = (Invoices) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a Invoices collection into a temporary file.
		/// </summary>
		private void Step_8_SerializeCollection_Generated()
		{
			string fileName = "temp_InvoicesCollection.xml";
		
			VList<Invoices> mockCollection = new VList<Invoices>();
			mockCollection.Add(mock);
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<Invoices>)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mockCollection); 
			myWriter.Close();
			
			System.Console.WriteLine("VList<Invoices> correctly serialized to a temporary file.");					
		}
		
		
		/// <summary>
		/// Deserialize a Invoices collection from a temporary file.
		/// </summary>
		private void Step_9_DeserializeCollection_Generated()
		{
			string fileName = "temp_InvoicesCollection.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<Invoices>)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			VList<Invoices> mockCollection = (VList<Invoices>) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("VList<Invoices> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		#region Mock Instance
		///<summary>
		///  Returns a Typed Invoices Entity with mock values.
		///</summary>
		static public Invoices CreateMockInstance()
		{		
			Invoices mock = new Invoices();
						
			mock.ShipName = TestUtility.Instance.RandomString(19, false);;
			mock.ShipAddress = TestUtility.Instance.RandomString(29, false);;
			mock.ShipCity = TestUtility.Instance.RandomString(6, false);;
			mock.ShipRegion = TestUtility.Instance.RandomString(6, false);;
			mock.ShipPostalCode = TestUtility.Instance.RandomString(10, false);;
			mock.ShipCountry = TestUtility.Instance.RandomString(6, false);;
			mock.CustomerId = TestUtility.Instance.RandomString(5, false);;
			mock.CustomerName = TestUtility.Instance.RandomString(19, false);;
			mock.Address = TestUtility.Instance.RandomString(29, false);;
			mock.City = TestUtility.Instance.RandomString(6, false);;
			mock.Region = TestUtility.Instance.RandomString(6, false);;
			mock.PostalCode = TestUtility.Instance.RandomString(10, false);;
			mock.Country = TestUtility.Instance.RandomString(6, false);;
			mock.Salesperson = TestUtility.Instance.RandomString(14, false);;
			mock.OrderId = TestUtility.Instance.RandomNumber();
			mock.OrderDate = TestUtility.Instance.RandomDateTime();
			mock.RequiredDate = TestUtility.Instance.RandomDateTime();
			mock.ShippedDate = TestUtility.Instance.RandomDateTime();
			mock.ShipperName = TestUtility.Instance.RandomString(19, false);;
			mock.ProductId = TestUtility.Instance.RandomNumber();
			mock.ProductName = TestUtility.Instance.RandomString(19, false);;
			mock.UnitPrice = TestUtility.Instance.RandomShort();
			mock.Quantity = TestUtility.Instance.RandomShort();
			mock.Discount = (float)TestUtility.Instance.RandomNumber();
			mock.ExtendedPrice = TestUtility.Instance.RandomShort();
			mock.Freight = TestUtility.Instance.RandomShort();
		   return (Invoices)mock;
		}
		

		#endregion
    }
}
