
/*
	File Generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file ProductsByCategoryTest.cs instead.
*/
#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using Northwind.Entities;
using Northwind.Data;

#endregion

namespace Northwind.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="ProductsByCategory"/> objects (entity, collection and repository).
    /// </summary>
    public partial class ProductsByCategoryTest
    {
    	// the ProductsByCategory instance used to test the repository.
		private ProductsByCategory mock;
		
		// the VList<ProductsByCategory> instance used to test the repository.
		private VList<ProductsByCategory> mockCollection;		

        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>
        static private void Init_Generated()
        {
			System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the ProductsByCategory Entity with the {0} --", Northwind.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
        static private void CleanUp_Generated()
        {       	
			System.Console.WriteLine();
			System.Console.WriteLine();
        }
		
		/// <summary>
		/// Selects a page of ProductsByCategory objects from the database.
		/// </summary>
		private void Step_1_SelectAll_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.ProductsByCategoryProvider.GetPaged(null, 0, 10, out count);
			Assert.IsTrue(count >= 0, "Select Query Failed with GetPaged");
			System.Console.WriteLine("DataRepository.ProductsByCategoryProvider.GetPaged():");			
			System.Console.WriteLine(mockCollection);			
		}
		
		/// <summary>
		/// Searches some ProductsByCategory objects from the database.
		/// </summary>
		private void Step_2_Search_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.ProductsByCategoryProvider.Find(null, null, "", 0, 10, out count);
			Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
			
			System.Console.WriteLine("DataRepository.ProductsByCategoryProvider.Find():");			
			System.Console.WriteLine(mockCollection);
					
		}
		 //Find
			
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock ProductsByCategory entity into a temporary file.
		/// </summary>
		private void Step_6_SerializeEntity_Generated()
		{
			string fileName = "temp_ProductsByCategory.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(ProductsByCategory)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mock); 
			myWriter.Close();
			System.Console.WriteLine("mock correctly serialized to a temporary file.");			
		}
		
		/// <summary>
		/// Deserialize the mock ProductsByCategory entity from a temporary file.
		/// </summary>
		private void Step_7_DeserializeEntity_Generated()
		{
			string fileName = "temp_ProductsByCategory.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(ProductsByCategory)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			mock = (ProductsByCategory) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a ProductsByCategory collection into a temporary file.
		/// </summary>
		private void Step_8_SerializeCollection_Generated()
		{
			string fileName = "temp_ProductsByCategoryCollection.xml";
		
			VList<ProductsByCategory> mockCollection = new VList<ProductsByCategory>();
			mockCollection.Add(mock);
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<ProductsByCategory>)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mockCollection); 
			myWriter.Close();
			
			System.Console.WriteLine("VList<ProductsByCategory> correctly serialized to a temporary file.");					
		}
		
		
		/// <summary>
		/// Deserialize a ProductsByCategory collection from a temporary file.
		/// </summary>
		private void Step_9_DeserializeCollection_Generated()
		{
			string fileName = "temp_ProductsByCategoryCollection.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<ProductsByCategory>)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			VList<ProductsByCategory> mockCollection = (VList<ProductsByCategory>) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("VList<ProductsByCategory> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		#region Mock Instance
		///<summary>
		///  Returns a Typed ProductsByCategory Entity with mock values.
		///</summary>
		static public ProductsByCategory CreateMockInstance()
		{		
			ProductsByCategory mock = new ProductsByCategory();
						
			mock.CategoryName = TestUtility.Instance.RandomString(6, false);;
			mock.ProductName = TestUtility.Instance.RandomString(19, false);;
			mock.QuantityPerUnit = TestUtility.Instance.RandomString(9, false);;
			mock.UnitsInStock = TestUtility.Instance.RandomShort();
			mock.Discontinued = TestUtility.Instance.RandomBoolean();
		   return (ProductsByCategory)mock;
		}
		

		#endregion
    }
}
