
/*
	File Generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file SummaryOfSalesByQuarterTest.cs instead.
*/
#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using Northwind.Entities;
using Northwind.Data;

#endregion

namespace Northwind.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="SummaryOfSalesByQuarter"/> objects (entity, collection and repository).
    /// </summary>
    public partial class SummaryOfSalesByQuarterTest
    {
    	// the SummaryOfSalesByQuarter instance used to test the repository.
		private SummaryOfSalesByQuarter mock;
		
		// the VList<SummaryOfSalesByQuarter> instance used to test the repository.
		private VList<SummaryOfSalesByQuarter> mockCollection;		

        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>
        static private void Init_Generated()
        {
			System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the SummaryOfSalesByQuarter Entity with the {0} --", Northwind.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
        static private void CleanUp_Generated()
        {       	
			System.Console.WriteLine();
			System.Console.WriteLine();
        }
		
		/// <summary>
		/// Selects a page of SummaryOfSalesByQuarter objects from the database.
		/// </summary>
		private void Step_1_SelectAll_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.SummaryOfSalesByQuarterProvider.GetPaged(null, 0, 10, out count);
			Assert.IsTrue(count >= 0, "Select Query Failed with GetPaged");
			System.Console.WriteLine("DataRepository.SummaryOfSalesByQuarterProvider.GetPaged():");			
			System.Console.WriteLine(mockCollection);			
		}
		
		/// <summary>
		/// Searches some SummaryOfSalesByQuarter objects from the database.
		/// </summary>
		private void Step_2_Search_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.SummaryOfSalesByQuarterProvider.Find(null, null, "", 0, 10, out count);
			Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
			
			System.Console.WriteLine("DataRepository.SummaryOfSalesByQuarterProvider.Find():");			
			System.Console.WriteLine(mockCollection);
					
		}
		 //Find
			
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock SummaryOfSalesByQuarter entity into a temporary file.
		/// </summary>
		private void Step_6_SerializeEntity_Generated()
		{
			string fileName = "temp_SummaryOfSalesByQuarter.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(SummaryOfSalesByQuarter)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mock); 
			myWriter.Close();
			System.Console.WriteLine("mock correctly serialized to a temporary file.");			
		}
		
		/// <summary>
		/// Deserialize the mock SummaryOfSalesByQuarter entity from a temporary file.
		/// </summary>
		private void Step_7_DeserializeEntity_Generated()
		{
			string fileName = "temp_SummaryOfSalesByQuarter.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(SummaryOfSalesByQuarter)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			mock = (SummaryOfSalesByQuarter) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a SummaryOfSalesByQuarter collection into a temporary file.
		/// </summary>
		private void Step_8_SerializeCollection_Generated()
		{
			string fileName = "temp_SummaryOfSalesByQuarterCollection.xml";
		
			VList<SummaryOfSalesByQuarter> mockCollection = new VList<SummaryOfSalesByQuarter>();
			mockCollection.Add(mock);
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<SummaryOfSalesByQuarter>)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mockCollection); 
			myWriter.Close();
			
			System.Console.WriteLine("VList<SummaryOfSalesByQuarter> correctly serialized to a temporary file.");					
		}
		
		
		/// <summary>
		/// Deserialize a SummaryOfSalesByQuarter collection from a temporary file.
		/// </summary>
		private void Step_9_DeserializeCollection_Generated()
		{
			string fileName = "temp_SummaryOfSalesByQuarterCollection.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<SummaryOfSalesByQuarter>)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			VList<SummaryOfSalesByQuarter> mockCollection = (VList<SummaryOfSalesByQuarter>) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("VList<SummaryOfSalesByQuarter> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		#region Mock Instance
		///<summary>
		///  Returns a Typed SummaryOfSalesByQuarter Entity with mock values.
		///</summary>
		static public SummaryOfSalesByQuarter CreateMockInstance()
		{		
			SummaryOfSalesByQuarter mock = new SummaryOfSalesByQuarter();
						
			mock.ShippedDate = TestUtility.Instance.RandomDateTime();
			mock.OrderId = TestUtility.Instance.RandomNumber();
			mock.Subtotal = TestUtility.Instance.RandomShort();
		   return (SummaryOfSalesByQuarter)mock;
		}
		

		#endregion
    }
}
