
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Categories.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using Northwind.Entities.Validation;
#endregion

namespace Northwind.Entities
{
	///<summary>
	/// An object representation of the 'Categories' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class CategoriesBase : EntityBase, ICategories, IEntityId<CategoriesKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private CategoriesEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private CategoriesEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private CategoriesEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Categories> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CategoriesEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CategoriesEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="CategoriesBase"/> instance.
		///</summary>
		public CategoriesBase()
		{
			this.entityData = new CategoriesEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="CategoriesBase"/> instance.
		///</summary>
		///<param name="_categoryName"></param>
		///<param name="_description"></param>
		///<param name="_picture"></param>
		public CategoriesBase(System.String _categoryName, System.String _description, System.Byte[] _picture)
		{
			this.entityData = new CategoriesEntityData();
			this.backupData = null;

			this.CategoryName = _categoryName;
			this.Description = _description;
			this.Picture = _picture;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Categories"/> instance.
		///</summary>
		///<param name="_categoryName"></param>
		///<param name="_description"></param>
		///<param name="_picture"></param>
		public static Categories CreateCategories(System.String _categoryName, System.String _description, System.Byte[] _picture)
		{
			Categories newCategories = new Categories();
			newCategories.CategoryName = _categoryName;
			newCategories.Description = _description;
			newCategories.Picture = _picture;
			return newCategories;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the CategoryId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 CategoryId
		{
			get
			{
				return this.entityData.CategoryId; 
			}
			
			set
			{
				if (this.entityData.CategoryId == value)
					return;
				
                OnPropertyChanging("CategoryId");                    
				OnColumnChanging(CategoriesColumn.CategoryId, this.entityData.CategoryId);
				this.entityData.CategoryId = value;
				this.EntityId.CategoryId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CategoriesColumn.CategoryId, this.entityData.CategoryId);
				OnPropertyChanged("CategoryId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CategoryName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 15)]
		public virtual System.String CategoryName
		{
			get
			{
				return this.entityData.CategoryName; 
			}
			
			set
			{
				if (this.entityData.CategoryName == value)
					return;
				
                OnPropertyChanging("CategoryName");                    
				OnColumnChanging(CategoriesColumn.CategoryName, this.entityData.CategoryName);
				this.entityData.CategoryName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CategoriesColumn.CategoryName, this.entityData.CategoryName);
				OnPropertyChanged("CategoryName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Description property. 
		///		
		/// </summary>
		/// <value>This type is ntext.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.String Description
		{
			get
			{
				return this.entityData.Description; 
			}
			
			set
			{
				if (this.entityData.Description == value)
					return;
				
                OnPropertyChanging("Description");                    
				OnColumnChanging(CategoriesColumn.Description, this.entityData.Description);
				this.entityData.Description = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CategoriesColumn.Description, this.entityData.Description);
				OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Picture property. 
		///		
		/// </summary>
		/// <value>This type is image.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Byte[] Picture
		{
			get
			{
				return this.entityData.Picture; 
			}
			
			set
			{
				if (this.entityData.Picture == value)
					return;
				
                OnPropertyChanging("Picture");                    
				OnColumnChanging(CategoriesColumn.Picture, this.entityData.Picture);
				this.entityData.Picture = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CategoriesColumn.Picture, this.entityData.Picture);
				OnPropertyChanged("Picture");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of Products objects
		///	which are related to this object through the relation FK_Products_Categories
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Products> ProductsCollection
		{
			get { return entityData.ProductsCollection; }
			set { entityData.ProductsCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("CategoryName", "Category Name"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("CategoryName", "Category Name", 15));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Categories"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"CategoryID", "CategoryName", "Description", "Picture"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as CategoriesEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Categories) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Categories>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Categories);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Categories Entity 
		///</summary>
		protected virtual Categories Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Categories copy = new Categories();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.CategoryId = this.CategoryId;
				copy.CategoryName = this.CategoryName;
				copy.Description = this.Description;
				copy.Picture = this.Picture;
			
		
			//deep copy nested objects
			copy.ProductsCollection = (TList<Products>) MakeCopyOf(this.ProductsCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Categories Entity 
		///</summary>
		public virtual Categories Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Categories Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Categories DeepCopy()
		{
			return EntityHelper.Clone<Categories>(this as Categories);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as CategoriesEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new CategoriesEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as CategoriesEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(CategoriesColumn column)
		{
			switch(column)
			{
					case CategoriesColumn.CategoryId:
					return entityData.CategoryId != _originalData.CategoryId;
					case CategoriesColumn.CategoryName:
					return entityData.CategoryName != _originalData.CategoryName;
					case CategoriesColumn.Description:
					return entityData.Description != _originalData.Description;
					case CategoriesColumn.Picture:
					return entityData.Picture != _originalData.Picture;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< CategoriesColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.CategoryId != _originalData.CategoryId;
			result = result || entityData.CategoryName != _originalData.CategoryName;
			result = result || entityData.Description != _originalData.Description;
			result = result || entityData.Picture != _originalData.Picture;
			return result;
		}	
		
		///<summary>
		///  Returns a Categories Entity with the original data.
		///</summary>
		public Categories GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateCategories(
				_originalData.CategoryName,
				_originalData.Description,
				_originalData.Picture
				);
				
			return (Categories)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="CategoriesBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is CategoriesBase)
				return ValueEquals(this, (CategoriesBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="CategoriesBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.CategoryId.GetHashCode() ^ 
					this.CategoryName.GetHashCode() ^ 
					((this.Description == null) ? string.Empty : this.Description.ToString()).GetHashCode() ^ 
					((this.Picture == null) ? string.Empty : this.Picture.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="CategoriesBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(CategoriesBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="CategoriesBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="CategoriesBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="CategoriesBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(CategoriesBase Object1, CategoriesBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.CategoryId != Object2.CategoryId)
				equal = false;
			if (Object1.CategoryName != Object2.CategoryName)
				equal = false;
			if ( Object1.Description != null && Object2.Description != null )
			{
				if (Object1.Description != Object2.Description)
					equal = false;
			}
			else if (Object1.Description == null ^ Object2.Description == null )
			{
				equal = false;
			}
			if ( Object1.Picture != null && Object2.Picture != null )
			{
				if (Object1.Picture != Object2.Picture)
					equal = false;
			}
			else if (Object1.Picture == null ^ Object2.Picture == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((CategoriesBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static CategoriesComparer GetComparer()
        {
            return new CategoriesComparer();
        }
        */

        // Comparer delegates back to Categories
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Categories rhs, CategoriesColumn which)
        {
            switch (which)
            {
            	
            	
            	case CategoriesColumn.CategoryId:
            		return this.CategoryId.CompareTo(rhs.CategoryId);
            		
            		                 
            	
            	
            	case CategoriesColumn.CategoryName:
            		return this.CategoryName.CompareTo(rhs.CategoryName);
            		
            		                 
            	
            	
            	case CategoriesColumn.Description:
            		return this.Description.CompareTo(rhs.Description);
            		
            		                 
            	
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<CategoriesKey> Members
		
		// member variable for the EntityId property
		private CategoriesKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual CategoriesKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new CategoriesKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Categories")
					.Append("|").Append( this.CategoryId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{5}{4}- CategoryId: {0}{4}- CategoryName: {1}{4}- Description: {2}{4}- Picture: {3}{4}{6}", 
				this.CategoryId,
				this.CategoryName,
				(this.Description == null) ? string.Empty : this.Description.ToString(),
				(this.Picture == null) ? string.Empty : this.Picture.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Categories' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class CategoriesEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// CategoryID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Categories"</remarks>
		public System.Int32 CategoryId;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// CategoryName : 
		/// </summary>
		public System.String CategoryName = string.Empty;
		
		/// <summary>
		/// Description : 
		/// </summary>
		public System.String Description = null;
		
		/// <summary>
		/// Picture : 
		/// </summary>
		public System.Byte[] Picture = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#region ProductsCollection
		
		private TList<Products> _productsCategoryId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _productsCategoryId
		/// </summary>
		
		public TList<Products> ProductsCollection
		{
			get
			{
				if (_productsCategoryId == null)
				{
				_productsCategoryId = new TList<Products>();
				}
	
				return _productsCategoryId;
			}
			set { _productsCategoryId = value; }
		}
		
		#endregion

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			CategoriesEntityData _tmp = new CategoriesEntityData();
						
			_tmp.CategoryId = this.CategoryId;
			
			_tmp.CategoryName = this.CategoryName;
			_tmp.Description = this.Description;
			_tmp.Picture = this.Picture;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._productsCategoryId != null)
				_tmp.ProductsCollection = (TList<Products>) MakeCopyOf(this.ProductsCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			CategoriesEntityData _tmp = new CategoriesEntityData();
						
			_tmp.CategoryId = this.CategoryId;
			
			_tmp.CategoryName = this.CategoryName;
			_tmp.Description = this.Description;
			_tmp.Picture = this.Picture;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.ProductsCollection = (TList<Products>) MakeCopyOf(this.ProductsCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CategoriesColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(CategoriesColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CategoriesColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(CategoriesColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CategoriesColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(CategoriesColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				CategoriesEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new CategoriesEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CategoriesColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(CategoriesColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				CategoriesEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new CategoriesEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region CategoriesEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Categories"/> object.
	/// </remarks>
	public class CategoriesEventArgs : System.EventArgs
	{
		private CategoriesColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the CategoriesEventArgs class.
		///</summary>
		public CategoriesEventArgs(CategoriesColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the CategoriesEventArgs class.
		///</summary>
		public CategoriesEventArgs(CategoriesColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The CategoriesColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="CategoriesColumn" />
		public CategoriesColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Categories related events.
	///</summary>
	public delegate void CategoriesEventHandler(object sender, CategoriesEventArgs e);
	
	#region CategoriesComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class CategoriesComparer : System.Collections.Generic.IComparer<Categories>
	{
		CategoriesColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:CategoriesComparer"/> class.
        /// </summary>
		public CategoriesComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:CategoriesComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public CategoriesComparer(CategoriesColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="Categories"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="Categories"/> to compare.</param>
        /// <param name="b">The second <c>Categories</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Categories a, Categories b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Categories entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Categories a, Categories b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public CategoriesColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region CategoriesKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Categories"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class CategoriesKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the CategoriesKey class.
		/// </summary>
		public CategoriesKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the CategoriesKey class.
		/// </summary>
		public CategoriesKey(CategoriesBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.CategoryId = entity.CategoryId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the CategoriesKey class.
		/// </summary>
		public CategoriesKey(System.Int32 _categoryId)
		{
			#region Init Properties

			this.CategoryId = _categoryId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private CategoriesBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public CategoriesBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the CategoryId property
		private System.Int32 _categoryId;
		
		/// <summary>
		/// Gets or sets the CategoryId property.
		/// </summary>
		public System.Int32 CategoryId
		{
			get { return _categoryId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.CategoryId = value;
				
				_categoryId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				CategoryId = ( values["CategoryId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["CategoryId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("CategoryId", CategoryId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("CategoryId: {0}{1}",
								CategoryId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region CategoriesColumn Enum
	
	/// <summary>
	/// Enumerate the Categories columns.
	/// </summary>
	[Serializable]
	public enum CategoriesColumn : int
	{
		/// <summary>
		/// CategoryId : 
		/// </summary>
		[EnumTextValue("CategoryID")]
		[ColumnEnum("CategoryID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		CategoryId = 1,
		/// <summary>
		/// CategoryName : 
		/// </summary>
		[EnumTextValue("CategoryName")]
		[ColumnEnum("CategoryName", typeof(System.String), System.Data.DbType.String, false, false, false, 15)]
		CategoryName = 2,
		/// <summary>
		/// Description : 
		/// </summary>
		[EnumTextValue("Description")]
		[ColumnEnum("Description", typeof(System.String), System.Data.DbType.String, false, false, true)]
		Description = 3,
		/// <summary>
		/// Picture : 
		/// </summary>
		[EnumTextValue("Picture")]
		[ColumnEnum("Picture", typeof(System.Byte[]), System.Data.DbType.Binary, false, false, true)]
		Picture = 4
	}//End enum

	#endregion CategoriesColumn Enum

} // end namespace
