
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file CustomerDemographics.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using Northwind.Entities.Validation;
#endregion

namespace Northwind.Entities
{
	///<summary>
	/// An object representation of the 'CustomerDemographics' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class CustomerDemographicsBase : EntityBase, ICustomerDemographics, IEntityId<CustomerDemographicsKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private CustomerDemographicsEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private CustomerDemographicsEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private CustomerDemographicsEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<CustomerDemographics> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CustomerDemographicsEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CustomerDemographicsEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="CustomerDemographicsBase"/> instance.
		///</summary>
		public CustomerDemographicsBase()
		{
			this.entityData = new CustomerDemographicsEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="CustomerDemographicsBase"/> instance.
		///</summary>
		///<param name="_customerTypeId"></param>
		///<param name="_customerDesc"></param>
		public CustomerDemographicsBase(System.String _customerTypeId, System.String _customerDesc)
		{
			this.entityData = new CustomerDemographicsEntityData();
			this.backupData = null;

			this.CustomerTypeId = _customerTypeId;
			this.CustomerDesc = _customerDesc;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="CustomerDemographics"/> instance.
		///</summary>
		///<param name="_customerTypeId"></param>
		///<param name="_customerDesc"></param>
		public static CustomerDemographics CreateCustomerDemographics(System.String _customerTypeId, System.String _customerDesc)
		{
			CustomerDemographics newCustomerDemographics = new CustomerDemographics();
			newCustomerDemographics.CustomerTypeId = _customerTypeId;
			newCustomerDemographics.CustomerDesc = _customerDesc;
			return newCustomerDemographics;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the CustomerTypeId property. 
		///		
		/// </summary>
		/// <value>This type is nchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false, 10)]
		public virtual System.String CustomerTypeId
		{
			get
			{
				return this.entityData.CustomerTypeId; 
			}
			
			set
			{
				if (this.entityData.CustomerTypeId == value)
					return;
				
                OnPropertyChanging("CustomerTypeId");                    
				OnColumnChanging(CustomerDemographicsColumn.CustomerTypeId, this.entityData.CustomerTypeId);
				this.entityData.CustomerTypeId = value;
				this.EntityId.CustomerTypeId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CustomerDemographicsColumn.CustomerTypeId, this.entityData.CustomerTypeId);
				OnPropertyChanged("CustomerTypeId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the CustomerTypeID property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the CustomerTypeID property.</remarks>
		/// <value>This type is nchar</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.String OriginalCustomerTypeId
		{
			get { return this.entityData.OriginalCustomerTypeId; }
			set { this.entityData.OriginalCustomerTypeId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the CustomerDesc property. 
		///		
		/// </summary>
		/// <value>This type is ntext.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.String CustomerDesc
		{
			get
			{
				return this.entityData.CustomerDesc; 
			}
			
			set
			{
				if (this.entityData.CustomerDesc == value)
					return;
				
                OnPropertyChanging("CustomerDesc");                    
				OnColumnChanging(CustomerDemographicsColumn.CustomerDesc, this.entityData.CustomerDesc);
				this.entityData.CustomerDesc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CustomerDemographicsColumn.CustomerDesc, this.entityData.CustomerDesc);
				OnPropertyChanged("CustomerDesc");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections

		/// <summary>
		///	Holds a collection of CustomersFromCustomerCustomerDemo objects
		///	which are related to this object through the junction table CustomerCustomerDemo
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Customers> CustomerIdCustomersCollection_From_CustomerCustomerDemo
		{
			get { return entityData.CustomerIdCustomersCollection_From_CustomerCustomerDemo; }
			set { entityData.CustomerIdCustomersCollection_From_CustomerCustomerDemo = value; }	
		}
	
		/// <summary>
		///	Holds a collection of CustomerCustomerDemo objects
		///	which are related to this object through the relation FK_CustomerCustomerDemo
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<CustomerCustomerDemo> CustomerCustomerDemoCollection
		{
			get { return entityData.CustomerCustomerDemoCollection; }
			set { entityData.CustomerCustomerDemoCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("CustomerTypeId", "Customer Type Id"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("CustomerTypeId", "Customer Type Id", 10));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "CustomerDemographics"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"CustomerTypeID", "CustomerDesc"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as CustomerDemographicsEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (CustomerDemographics) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<CustomerDemographics>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as CustomerDemographics);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed CustomerDemographics Entity 
		///</summary>
		protected virtual CustomerDemographics Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			CustomerDemographics copy = new CustomerDemographics();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.CustomerTypeId = this.CustomerTypeId;
					copy.OriginalCustomerTypeId = this.OriginalCustomerTypeId;
				copy.CustomerDesc = this.CustomerDesc;
			
		
			//deep copy nested objects
			copy.CustomerIdCustomersCollection_From_CustomerCustomerDemo = (TList<Customers>) MakeCopyOf(this.CustomerIdCustomersCollection_From_CustomerCustomerDemo, existingCopies); 
			copy.CustomerCustomerDemoCollection = (TList<CustomerCustomerDemo>) MakeCopyOf(this.CustomerCustomerDemoCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed CustomerDemographics Entity 
		///</summary>
		public virtual CustomerDemographics Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed CustomerDemographics Entity which is a deep copy of the current entity.
		///</summary>
		public virtual CustomerDemographics DeepCopy()
		{
			return EntityHelper.Clone<CustomerDemographics>(this as CustomerDemographics);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as CustomerDemographicsEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new CustomerDemographicsEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as CustomerDemographicsEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(CustomerDemographicsColumn column)
		{
			switch(column)
			{
					case CustomerDemographicsColumn.CustomerTypeId:
					return entityData.CustomerTypeId != _originalData.CustomerTypeId;
					case CustomerDemographicsColumn.CustomerDesc:
					return entityData.CustomerDesc != _originalData.CustomerDesc;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< CustomerDemographicsColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.CustomerTypeId != _originalData.CustomerTypeId;
			result = result || entityData.CustomerDesc != _originalData.CustomerDesc;
			return result;
		}	
		
		///<summary>
		///  Returns a CustomerDemographics Entity with the original data.
		///</summary>
		public CustomerDemographics GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateCustomerDemographics(
				_originalData.CustomerTypeId,
				_originalData.CustomerDesc
				);
				
			return (CustomerDemographics)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="CustomerDemographicsBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is CustomerDemographicsBase)
				return ValueEquals(this, (CustomerDemographicsBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="CustomerDemographicsBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.CustomerTypeId.GetHashCode() ^ 
					((this.CustomerDesc == null) ? string.Empty : this.CustomerDesc.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="CustomerDemographicsBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(CustomerDemographicsBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="CustomerDemographicsBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="CustomerDemographicsBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="CustomerDemographicsBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(CustomerDemographicsBase Object1, CustomerDemographicsBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.CustomerTypeId != Object2.CustomerTypeId)
				equal = false;
			if ( Object1.CustomerDesc != null && Object2.CustomerDesc != null )
			{
				if (Object1.CustomerDesc != Object2.CustomerDesc)
					equal = false;
			}
			else if (Object1.CustomerDesc == null ^ Object2.CustomerDesc == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((CustomerDemographicsBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static CustomerDemographicsComparer GetComparer()
        {
            return new CustomerDemographicsComparer();
        }
        */

        // Comparer delegates back to CustomerDemographics
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(CustomerDemographics rhs, CustomerDemographicsColumn which)
        {
            switch (which)
            {
            	
            	
            	case CustomerDemographicsColumn.CustomerTypeId:
            		return this.CustomerTypeId.CompareTo(rhs.CustomerTypeId);
            		
            		                 
            	
            	
            	case CustomerDemographicsColumn.CustomerDesc:
            		return this.CustomerDesc.CompareTo(rhs.CustomerDesc);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<CustomerDemographicsKey> Members
		
		// member variable for the EntityId property
		private CustomerDemographicsKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual CustomerDemographicsKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new CustomerDemographicsKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("CustomerDemographics")
					.Append("|").Append( this.CustomerTypeId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{3}{2}- CustomerTypeId: {0}{2}- CustomerDesc: {1}{2}{4}", 
				this.CustomerTypeId,
				(this.CustomerDesc == null) ? string.Empty : this.CustomerDesc.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'CustomerDemographics' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class CustomerDemographicsEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// CustomerTypeID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "CustomerDemographics"</remarks>
		public System.String CustomerTypeId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.String OriginalCustomerTypeId;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// CustomerDesc : 
		/// </summary>
		public System.String CustomerDesc = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#region CustomerIdCustomersCollection_From_CustomerCustomerDemo
		
		private TList<Customers> customerIdCustomersCollectionFromCustomerCustomerDemo;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the junction table customerIdCustomersCollectionFromCustomerCustomerDemo
		/// </summary>
		
		public TList<Customers> CustomerIdCustomersCollection_From_CustomerCustomerDemo
		{
			get
			{
				if (customerIdCustomersCollectionFromCustomerCustomerDemo == null)
				{
				customerIdCustomersCollectionFromCustomerCustomerDemo = new TList<Customers>();
				}
	
				return customerIdCustomersCollectionFromCustomerCustomerDemo;
			}
			set { customerIdCustomersCollectionFromCustomerCustomerDemo = value; }
		}
		
		#endregion 

		#region CustomerCustomerDemoCollection
		
		private TList<CustomerCustomerDemo> _customerCustomerDemoCustomerTypeId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _customerCustomerDemoCustomerTypeId
		/// </summary>
		
		public TList<CustomerCustomerDemo> CustomerCustomerDemoCollection
		{
			get
			{
				if (_customerCustomerDemoCustomerTypeId == null)
				{
				_customerCustomerDemoCustomerTypeId = new TList<CustomerCustomerDemo>();
				}
	
				return _customerCustomerDemoCustomerTypeId;
			}
			set { _customerCustomerDemoCustomerTypeId = value; }
		}
		
		#endregion

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			CustomerDemographicsEntityData _tmp = new CustomerDemographicsEntityData();
						
			_tmp.CustomerTypeId = this.CustomerTypeId;
			_tmp.OriginalCustomerTypeId = this.OriginalCustomerTypeId;
			
			_tmp.CustomerDesc = this.CustomerDesc;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this.customerIdCustomersCollectionFromCustomerCustomerDemo != null)
				_tmp.CustomerIdCustomersCollection_From_CustomerCustomerDemo = (TList<Customers>) MakeCopyOf(this.CustomerIdCustomersCollection_From_CustomerCustomerDemo); 
			if (this._customerCustomerDemoCustomerTypeId != null)
				_tmp.CustomerCustomerDemoCollection = (TList<CustomerCustomerDemo>) MakeCopyOf(this.CustomerCustomerDemoCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			CustomerDemographicsEntityData _tmp = new CustomerDemographicsEntityData();
						
			_tmp.CustomerTypeId = this.CustomerTypeId;
			_tmp.OriginalCustomerTypeId = this.OriginalCustomerTypeId;
			
			_tmp.CustomerDesc = this.CustomerDesc;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.CustomerIdCustomersCollection_From_CustomerCustomerDemo = (TList<Customers>) MakeCopyOf(this.CustomerIdCustomersCollection_From_CustomerCustomerDemo, existingCopies); 
			_tmp.CustomerCustomerDemoCollection = (TList<CustomerCustomerDemo>) MakeCopyOf(this.CustomerCustomerDemoCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CustomerDemographicsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(CustomerDemographicsColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CustomerDemographicsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(CustomerDemographicsColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CustomerDemographicsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(CustomerDemographicsColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				CustomerDemographicsEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new CustomerDemographicsEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CustomerDemographicsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(CustomerDemographicsColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				CustomerDemographicsEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new CustomerDemographicsEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region CustomerDemographicsEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="CustomerDemographics"/> object.
	/// </remarks>
	public class CustomerDemographicsEventArgs : System.EventArgs
	{
		private CustomerDemographicsColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the CustomerDemographicsEventArgs class.
		///</summary>
		public CustomerDemographicsEventArgs(CustomerDemographicsColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the CustomerDemographicsEventArgs class.
		///</summary>
		public CustomerDemographicsEventArgs(CustomerDemographicsColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The CustomerDemographicsColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="CustomerDemographicsColumn" />
		public CustomerDemographicsColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all CustomerDemographics related events.
	///</summary>
	public delegate void CustomerDemographicsEventHandler(object sender, CustomerDemographicsEventArgs e);
	
	#region CustomerDemographicsComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class CustomerDemographicsComparer : System.Collections.Generic.IComparer<CustomerDemographics>
	{
		CustomerDemographicsColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:CustomerDemographicsComparer"/> class.
        /// </summary>
		public CustomerDemographicsComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:CustomerDemographicsComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public CustomerDemographicsComparer(CustomerDemographicsColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="CustomerDemographics"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="CustomerDemographics"/> to compare.</param>
        /// <param name="b">The second <c>CustomerDemographics</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(CustomerDemographics a, CustomerDemographics b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(CustomerDemographics entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(CustomerDemographics a, CustomerDemographics b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public CustomerDemographicsColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region CustomerDemographicsKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="CustomerDemographics"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class CustomerDemographicsKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the CustomerDemographicsKey class.
		/// </summary>
		public CustomerDemographicsKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the CustomerDemographicsKey class.
		/// </summary>
		public CustomerDemographicsKey(CustomerDemographicsBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.CustomerTypeId = entity.CustomerTypeId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the CustomerDemographicsKey class.
		/// </summary>
		public CustomerDemographicsKey(System.String _customerTypeId)
		{
			#region Init Properties

			this.CustomerTypeId = _customerTypeId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private CustomerDemographicsBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public CustomerDemographicsBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the CustomerTypeId property
		private System.String _customerTypeId;
		
		/// <summary>
		/// Gets or sets the CustomerTypeId property.
		/// </summary>
		public System.String CustomerTypeId
		{
			get { return _customerTypeId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.CustomerTypeId = value;
				
				_customerTypeId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				CustomerTypeId = ( values["CustomerTypeId"] != null ) ? (System.String) EntityUtil.ChangeType(values["CustomerTypeId"], typeof(System.String)) : string.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("CustomerTypeId", CustomerTypeId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("CustomerTypeId: {0}{1}",
								CustomerTypeId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region CustomerDemographicsColumn Enum
	
	/// <summary>
	/// Enumerate the CustomerDemographics columns.
	/// </summary>
	[Serializable]
	public enum CustomerDemographicsColumn : int
	{
		/// <summary>
		/// CustomerTypeId : 
		/// </summary>
		[EnumTextValue("CustomerTypeID")]
		[ColumnEnum("CustomerTypeID", typeof(System.String), System.Data.DbType.StringFixedLength, true, false, false, 10)]
		CustomerTypeId = 1,
		/// <summary>
		/// CustomerDesc : 
		/// </summary>
		[EnumTextValue("CustomerDesc")]
		[ColumnEnum("CustomerDesc", typeof(System.String), System.Data.DbType.String, false, false, true)]
		CustomerDesc = 2
	}//End enum

	#endregion CustomerDemographicsColumn Enum

} // end namespace
