using System;
using System.ComponentModel;

namespace Northwind.Entities
{
	/// <summary>
	///		The data structure representation of the 'CustomerDemographics' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ICustomerDemographics 
	{
		/// <summary>			
		/// CustomerTypeID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "CustomerDemographics"</remarks>
		System.String CustomerTypeId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalCustomerTypeId { get; set; }
			
		
		
		/// <summary>
		/// CustomerDesc : 
		/// </summary>
		System.String  CustomerDesc  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the junction table customerIdCustomersCollectionFromCustomerCustomerDemo
		/// </summary>	
		TList<Customers> CustomerIdCustomersCollection_From_CustomerCustomerDemo { get; set; }	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _customerCustomerDemoCustomerTypeId
		/// </summary>	
		TList<CustomerCustomerDemo> CustomerCustomerDemoCollection {  get;  set;}	

		#endregion Data Properties

	}
}


