/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file AlphabeticalListOfProducts.cs instead.
*/
#region Using Directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Runtime.Serialization;
using System.Xml.Serialization;
#endregion

namespace Northwind.Entities
{
	///<summary>
	/// An object representation of the 'Alphabetical list of products' view. [No description found in the database]	
	///</summary>
	[Serializable]
	[CLSCompliant(true)]
	[ToolboxItem("AlphabeticalListOfProductsBase")]
	public abstract partial class AlphabeticalListOfProductsBase : System.IComparable, System.ICloneable, INotifyPropertyChanged
	{
		
		#region Variable Declarations
		
		/// <summary>
		/// ProductID : 
		/// </summary>
		private System.Int32		  _productId = (int)0;
		
		/// <summary>
		/// ProductName : 
		/// </summary>
		private System.String		  _productName = string.Empty;
		
		/// <summary>
		/// SupplierID : 
		/// </summary>
		private System.Int32?		  _supplierId = null;
		
		/// <summary>
		/// CategoryID : 
		/// </summary>
		private System.Int32?		  _categoryId = null;
		
		/// <summary>
		/// QuantityPerUnit : 
		/// </summary>
		private System.String		  _quantityPerUnit = null;
		
		/// <summary>
		/// UnitPrice : 
		/// </summary>
		private System.Decimal?		  _unitPrice = null;
		
		/// <summary>
		/// UnitsInStock : 
		/// </summary>
		private System.Int16?		  _unitsInStock = null;
		
		/// <summary>
		/// UnitsOnOrder : 
		/// </summary>
		private System.Int16?		  _unitsOnOrder = null;
		
		/// <summary>
		/// ReorderLevel : 
		/// </summary>
		private System.Int16?		  _reorderLevel = null;
		
		/// <summary>
		/// Discontinued : 
		/// </summary>
		private System.Boolean		  _discontinued = false;
		
		/// <summary>
		/// CategoryName : 
		/// </summary>
		private System.String		  _categoryName = string.Empty;
		
		/// <summary>
		/// Object that contains data to associate with this object
		/// </summary>
		private object _tag;
		
		/// <summary>
		/// Suppresses Entity Events from Firing, 
		/// useful when loading the entities from the database.
		/// </summary>
	    [NonSerialized] 
		private bool suppressEntityEvents = false;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="AlphabeticalListOfProductsBase"/> instance.
		///</summary>
		public AlphabeticalListOfProductsBase()
		{
		}		
		
		///<summary>
		/// Creates a new <see cref="AlphabeticalListOfProductsBase"/> instance.
		///</summary>
		///<param name="_productId"></param>
		///<param name="_productName"></param>
		///<param name="_supplierId"></param>
		///<param name="_categoryId"></param>
		///<param name="_quantityPerUnit"></param>
		///<param name="_unitPrice"></param>
		///<param name="_unitsInStock"></param>
		///<param name="_unitsOnOrder"></param>
		///<param name="_reorderLevel"></param>
		///<param name="_discontinued"></param>
		///<param name="_categoryName"></param>
		public AlphabeticalListOfProductsBase(System.Int32 _productId, System.String _productName, System.Int32? _supplierId, System.Int32? _categoryId, System.String _quantityPerUnit, System.Decimal? _unitPrice, System.Int16? _unitsInStock, System.Int16? _unitsOnOrder, System.Int16? _reorderLevel, System.Boolean _discontinued, System.String _categoryName)
		{
			this._productId = _productId;
			this._productName = _productName;
			this._supplierId = _supplierId;
			this._categoryId = _categoryId;
			this._quantityPerUnit = _quantityPerUnit;
			this._unitPrice = _unitPrice;
			this._unitsInStock = _unitsInStock;
			this._unitsOnOrder = _unitsOnOrder;
			this._reorderLevel = _reorderLevel;
			this._discontinued = _discontinued;
			this._categoryName = _categoryName;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="AlphabeticalListOfProducts"/> instance.
		///</summary>
		///<param name="_productId"></param>
		///<param name="_productName"></param>
		///<param name="_supplierId"></param>
		///<param name="_categoryId"></param>
		///<param name="_quantityPerUnit"></param>
		///<param name="_unitPrice"></param>
		///<param name="_unitsInStock"></param>
		///<param name="_unitsOnOrder"></param>
		///<param name="_reorderLevel"></param>
		///<param name="_discontinued"></param>
		///<param name="_categoryName"></param>
		public static AlphabeticalListOfProducts CreateAlphabeticalListOfProducts(System.Int32 _productId, System.String _productName, System.Int32? _supplierId, System.Int32? _categoryId, System.String _quantityPerUnit, System.Decimal? _unitPrice, System.Int16? _unitsInStock, System.Int16? _unitsOnOrder, System.Int16? _reorderLevel, System.Boolean _discontinued, System.String _categoryName)
		{
			AlphabeticalListOfProducts newAlphabeticalListOfProducts = new AlphabeticalListOfProducts();
			newAlphabeticalListOfProducts.ProductId = _productId;
			newAlphabeticalListOfProducts.ProductName = _productName;
			newAlphabeticalListOfProducts.SupplierId = _supplierId;
			newAlphabeticalListOfProducts.CategoryId = _categoryId;
			newAlphabeticalListOfProducts.QuantityPerUnit = _quantityPerUnit;
			newAlphabeticalListOfProducts.UnitPrice = _unitPrice;
			newAlphabeticalListOfProducts.UnitsInStock = _unitsInStock;
			newAlphabeticalListOfProducts.UnitsOnOrder = _unitsOnOrder;
			newAlphabeticalListOfProducts.ReorderLevel = _reorderLevel;
			newAlphabeticalListOfProducts.Discontinued = _discontinued;
			newAlphabeticalListOfProducts.CategoryName = _categoryName;
			return newAlphabeticalListOfProducts;
		}
				
		#endregion Constructors
		
		#region Properties	
		/// <summary>
		/// 	Gets or Sets the ProductID property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32 ProductId
		{
			get
			{
				return this._productId; 
			}
			set
			{
				if (_productId == value)
					return;
					
				this._productId = value;
				this._isDirty = true;
				
				OnPropertyChanged("ProductId");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the ProductName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String ProductName
		{
			get
			{
				return this._productName; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "ProductName does not allow null values.");
				if (_productName == value)
					return;
					
				this._productName = value;
				this._isDirty = true;
				
				OnPropertyChanged("ProductName");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the SupplierID property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsSupplierIdNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32? SupplierId
		{
			get
			{
				return this._supplierId; 
			}
			set
			{
				if (_supplierId == value && SupplierId != null )
					return;
					
				this._supplierId = value;
				this._isDirty = true;
				
				OnPropertyChanged("SupplierId");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the CategoryID property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsCategoryIdNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32? CategoryId
		{
			get
			{
				return this._categoryId; 
			}
			set
			{
				if (_categoryId == value && CategoryId != null )
					return;
					
				this._categoryId = value;
				this._isDirty = true;
				
				OnPropertyChanged("CategoryId");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the QuantityPerUnit property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String QuantityPerUnit
		{
			get
			{
				return this._quantityPerUnit; 
			}
			set
			{
				if (_quantityPerUnit == value)
					return;
					
				this._quantityPerUnit = value;
				this._isDirty = true;
				
				OnPropertyChanged("QuantityPerUnit");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the UnitPrice property. 
		///		
		/// </summary>
		/// <value>This type is money</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0. It is up to the developer
		/// to check the value of IsUnitPriceNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? UnitPrice
		{
			get
			{
				return this._unitPrice; 
			}
			set
			{
				if (_unitPrice == value && UnitPrice != null )
					return;
					
				this._unitPrice = value;
				this._isDirty = true;
				
				OnPropertyChanged("UnitPrice");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the UnitsInStock property. 
		///		
		/// </summary>
		/// <value>This type is smallint</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (short)0. It is up to the developer
		/// to check the value of IsUnitsInStockNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int16? UnitsInStock
		{
			get
			{
				return this._unitsInStock; 
			}
			set
			{
				if (_unitsInStock == value && UnitsInStock != null )
					return;
					
				this._unitsInStock = value;
				this._isDirty = true;
				
				OnPropertyChanged("UnitsInStock");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the UnitsOnOrder property. 
		///		
		/// </summary>
		/// <value>This type is smallint</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (short)0. It is up to the developer
		/// to check the value of IsUnitsOnOrderNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int16? UnitsOnOrder
		{
			get
			{
				return this._unitsOnOrder; 
			}
			set
			{
				if (_unitsOnOrder == value && UnitsOnOrder != null )
					return;
					
				this._unitsOnOrder = value;
				this._isDirty = true;
				
				OnPropertyChanged("UnitsOnOrder");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the ReorderLevel property. 
		///		
		/// </summary>
		/// <value>This type is smallint</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (short)0. It is up to the developer
		/// to check the value of IsReorderLevelNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int16? ReorderLevel
		{
			get
			{
				return this._reorderLevel; 
			}
			set
			{
				if (_reorderLevel == value && ReorderLevel != null )
					return;
					
				this._reorderLevel = value;
				this._isDirty = true;
				
				OnPropertyChanged("ReorderLevel");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Discontinued property. 
		///		
		/// </summary>
		/// <value>This type is bit</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Boolean Discontinued
		{
			get
			{
				return this._discontinued; 
			}
			set
			{
				if (_discontinued == value)
					return;
					
				this._discontinued = value;
				this._isDirty = true;
				
				OnPropertyChanged("Discontinued");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the CategoryName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String CategoryName
		{
			get
			{
				return this._categoryName; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "CategoryName does not allow null values.");
				if (_categoryName == value)
					return;
					
				this._categoryName = value;
				this._isDirty = true;
				
				OnPropertyChanged("CategoryName");
			}
		}
		
		
		/// <summary>
		///     Gets or sets the object that contains supplemental data about this object.
		/// </summary>
		/// <value>Object</value>
		[System.ComponentModel.Bindable(false)]
		[LocalizableAttribute(false)]
		[DescriptionAttribute("Object containing data to be associated with this object")]
		public virtual object Tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if (this._tag == value)
					return;
		
				this._tag = value;
			}
		}
	
		/// <summary>
		/// Determines whether this entity is to suppress events while set to true.
		/// </summary>
		[System.ComponentModel.Bindable(false)]
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public bool SuppressEntityEvents
		{	
			get
			{
				return suppressEntityEvents;
			}
			set
			{
				suppressEntityEvents = value;
			}	
		}

		private bool _isDeleted = false;
		/// <summary>
		/// Gets a value indicating if object has been <see cref="MarkToDelete"/>. ReadOnly.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDeleted
		{
			get { return this._isDeleted; }
		}


		private bool _isDirty = false;
		/// <summary>
		///	Gets a value indicating  if the object has been modified from its original state.
		/// </summary>
		///<value>True if object has been modified from its original state; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDirty
		{
			get { return this._isDirty; }
		}
		

		private bool _isNew = true;
		/// <summary>
		///	Gets a value indicating if the object is new.
		/// </summary>
		///<value>True if objectis new; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsNew
		{
			get { return this._isNew; }
			set { this._isNew = value; }
		}

		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public string ViewName
		{
			get { return "Alphabetical list of products"; }
		}

		
		#endregion
		
		#region Methods	
		
		/// <summary>
		/// Accepts the changes made to this object by setting each flags to false.
		/// </summary>
		public virtual void AcceptChanges()
		{
			this._isDeleted = false;
			this._isDirty = false;
			this._isNew = false;
			OnPropertyChanged(string.Empty);
		}
		
		
		///<summary>
		///  Revert all changes and restore original values.
		///  Currently not supported.
		///</summary>
		/// <exception cref="NotSupportedException">This method is not currently supported and always throws this exception.</exception>
		public virtual void CancelChanges()
		{
			throw new NotSupportedException("Method currently not Supported.");
		}
		
		///<summary>
		///   Marks entity to be deleted.
		///</summary>
		public virtual void MarkToDelete()
		{
			this._isDeleted = true;
		}
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed AlphabeticalListOfProductsBase Entity 
		///</summary>
		public virtual AlphabeticalListOfProductsBase Copy()
		{
			//shallow copy entity
			AlphabeticalListOfProducts copy = new AlphabeticalListOfProducts();
				copy.ProductId = this.ProductId;
				copy.ProductName = this.ProductName;
				copy.SupplierId = this.SupplierId;
				copy.CategoryId = this.CategoryId;
				copy.QuantityPerUnit = this.QuantityPerUnit;
				copy.UnitPrice = this.UnitPrice;
				copy.UnitsInStock = this.UnitsInStock;
				copy.UnitsOnOrder = this.UnitsOnOrder;
				copy.ReorderLevel = this.ReorderLevel;
				copy.Discontinued = this.Discontinued;
				copy.CategoryName = this.CategoryName;
			copy.AcceptChanges();
			return (AlphabeticalListOfProducts)copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Deep Copy of this entity.
		///</summary>
		public object Clone(){
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		#endregion
		
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="AlphabeticalListOfProductsBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(AlphabeticalListOfProductsBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="AlphabeticalListOfProductsBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="AlphabeticalListOfProductsBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="AlphabeticalListOfProductsBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(AlphabeticalListOfProductsBase Object1, AlphabeticalListOfProductsBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;

			bool equal = true;
			if (Object1.ProductId != Object2.ProductId)
				equal = false;
			if (Object1.ProductName != Object2.ProductName)
				equal = false;
			if (Object1.SupplierId != null && Object2.SupplierId != null )
			{
				if (Object1.SupplierId != Object2.SupplierId)
					equal = false;
			}
			else if (Object1.SupplierId == null ^ Object1.SupplierId == null )
			{
				equal = false;
			}
			if (Object1.CategoryId != null && Object2.CategoryId != null )
			{
				if (Object1.CategoryId != Object2.CategoryId)
					equal = false;
			}
			else if (Object1.CategoryId == null ^ Object1.CategoryId == null )
			{
				equal = false;
			}
			if (Object1.QuantityPerUnit != null && Object2.QuantityPerUnit != null )
			{
				if (Object1.QuantityPerUnit != Object2.QuantityPerUnit)
					equal = false;
			}
			else if (Object1.QuantityPerUnit == null ^ Object1.QuantityPerUnit == null )
			{
				equal = false;
			}
			if (Object1.UnitPrice != null && Object2.UnitPrice != null )
			{
				if (Object1.UnitPrice != Object2.UnitPrice)
					equal = false;
			}
			else if (Object1.UnitPrice == null ^ Object1.UnitPrice == null )
			{
				equal = false;
			}
			if (Object1.UnitsInStock != null && Object2.UnitsInStock != null )
			{
				if (Object1.UnitsInStock != Object2.UnitsInStock)
					equal = false;
			}
			else if (Object1.UnitsInStock == null ^ Object1.UnitsInStock == null )
			{
				equal = false;
			}
			if (Object1.UnitsOnOrder != null && Object2.UnitsOnOrder != null )
			{
				if (Object1.UnitsOnOrder != Object2.UnitsOnOrder)
					equal = false;
			}
			else if (Object1.UnitsOnOrder == null ^ Object1.UnitsOnOrder == null )
			{
				equal = false;
			}
			if (Object1.ReorderLevel != null && Object2.ReorderLevel != null )
			{
				if (Object1.ReorderLevel != Object2.ReorderLevel)
					equal = false;
			}
			else if (Object1.ReorderLevel == null ^ Object1.ReorderLevel == null )
			{
				equal = false;
			}
			if (Object1.Discontinued != Object2.Discontinued)
				equal = false;
			if (Object1.CategoryName != Object2.CategoryName)
				equal = false;
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
		}
	
		#endregion
		
		#region INotifyPropertyChanged Members
		
		/// <summary>
      /// Event to indicate that a property has changed.
      /// </summary>
		[field:NonSerialized]
		public event PropertyChangedEventHandler PropertyChanged;

		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="propertyName">The name of the property that has changed.</param>
		protected virtual void OnPropertyChanged(string propertyName)
		{ 
			OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
		}
		
		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="e">PropertyChangedEventArgs</param>
		protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
		{
			if (!SuppressEntityEvents)
			{
				if (null != PropertyChanged)
				{
					PropertyChanged(this, e);
				}
			}
		}
		
		#endregion
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="entity">The entity.</param>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public static object GetPropertyValueByName(AlphabeticalListOfProducts entity, string propertyName)
		{
			switch (propertyName)
			{
				case "ProductId":
					return entity.ProductId;
				case "ProductName":
					return entity.ProductName;
				case "SupplierId":
					return entity.SupplierId;
				case "CategoryId":
					return entity.CategoryId;
				case "QuantityPerUnit":
					return entity.QuantityPerUnit;
				case "UnitPrice":
					return entity.UnitPrice;
				case "UnitsInStock":
					return entity.UnitsInStock;
				case "UnitsOnOrder":
					return entity.UnitsOnOrder;
				case "ReorderLevel":
					return entity.ReorderLevel;
				case "Discontinued":
					return entity.Discontinued;
				case "CategoryName":
					return entity.CategoryName;
			}
			return null;
		}
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public object GetPropertyValueByName(string propertyName)
		{			
			return GetPropertyValueByName(this as AlphabeticalListOfProducts, propertyName);
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{12}{11}- ProductId: {0}{11}- ProductName: {1}{11}- SupplierId: {2}{11}- CategoryId: {3}{11}- QuantityPerUnit: {4}{11}- UnitPrice: {5}{11}- UnitsInStock: {6}{11}- UnitsOnOrder: {7}{11}- ReorderLevel: {8}{11}- Discontinued: {9}{11}- CategoryName: {10}{11}", 
				this.ProductId,
				this.ProductName,
				(this.SupplierId == null) ? string.Empty : this.SupplierId.ToString(),
			     
				(this.CategoryId == null) ? string.Empty : this.CategoryId.ToString(),
			     
				(this.QuantityPerUnit == null) ? string.Empty : this.QuantityPerUnit.ToString(),
			     
				(this.UnitPrice == null) ? string.Empty : this.UnitPrice.ToString(),
			     
				(this.UnitsInStock == null) ? string.Empty : this.UnitsInStock.ToString(),
			     
				(this.UnitsOnOrder == null) ? string.Empty : this.UnitsOnOrder.ToString(),
			     
				(this.ReorderLevel == null) ? string.Empty : this.ReorderLevel.ToString(),
			     
				this.Discontinued,
				this.CategoryName,
				System.Environment.NewLine, 
				this.GetType());
		}
	
	}//End Class
	
	
	/// <summary>
	/// Enumerate the AlphabeticalListOfProducts columns.
	/// </summary>
	[Serializable]
	public enum AlphabeticalListOfProductsColumn
	{
		/// <summary>
		/// ProductID : 
		/// </summary>
		[EnumTextValue("ProductID")]
		[ColumnEnum("ProductID", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		ProductId,
		/// <summary>
		/// ProductName : 
		/// </summary>
		[EnumTextValue("ProductName")]
		[ColumnEnum("ProductName", typeof(System.String), System.Data.DbType.String, false, false, false, 40)]
		ProductName,
		/// <summary>
		/// SupplierID : 
		/// </summary>
		[EnumTextValue("SupplierID")]
		[ColumnEnum("SupplierID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		SupplierId,
		/// <summary>
		/// CategoryID : 
		/// </summary>
		[EnumTextValue("CategoryID")]
		[ColumnEnum("CategoryID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		CategoryId,
		/// <summary>
		/// QuantityPerUnit : 
		/// </summary>
		[EnumTextValue("QuantityPerUnit")]
		[ColumnEnum("QuantityPerUnit", typeof(System.String), System.Data.DbType.String, false, false, true, 20)]
		QuantityPerUnit,
		/// <summary>
		/// UnitPrice : 
		/// </summary>
		[EnumTextValue("UnitPrice")]
		[ColumnEnum("UnitPrice", typeof(System.Decimal), System.Data.DbType.Currency, false, false, true)]
		UnitPrice,
		/// <summary>
		/// UnitsInStock : 
		/// </summary>
		[EnumTextValue("UnitsInStock")]
		[ColumnEnum("UnitsInStock", typeof(System.Int16), System.Data.DbType.Int16, false, false, true)]
		UnitsInStock,
		/// <summary>
		/// UnitsOnOrder : 
		/// </summary>
		[EnumTextValue("UnitsOnOrder")]
		[ColumnEnum("UnitsOnOrder", typeof(System.Int16), System.Data.DbType.Int16, false, false, true)]
		UnitsOnOrder,
		/// <summary>
		/// ReorderLevel : 
		/// </summary>
		[EnumTextValue("ReorderLevel")]
		[ColumnEnum("ReorderLevel", typeof(System.Int16), System.Data.DbType.Int16, false, false, true)]
		ReorderLevel,
		/// <summary>
		/// Discontinued : 
		/// </summary>
		[EnumTextValue("Discontinued")]
		[ColumnEnum("Discontinued", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, false)]
		Discontinued,
		/// <summary>
		/// CategoryName : 
		/// </summary>
		[EnumTextValue("CategoryName")]
		[ColumnEnum("CategoryName", typeof(System.String), System.Data.DbType.String, false, false, false, 15)]
		CategoryName
	}//End enum

} // end namespace
