/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file SalesTotalsByAmount.cs instead.
*/
#region Using Directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Runtime.Serialization;
using System.Xml.Serialization;
#endregion

namespace Northwind.Entities
{
	///<summary>
	/// An object representation of the 'Sales Totals by Amount' view. [No description found in the database]	
	///</summary>
	[Serializable]
	[CLSCompliant(true)]
	public abstract partial class SalesTotalsByAmountBase : System.IComparable, System.ICloneable, INotifyPropertyChanged
	{
		
		#region Variable Declarations
		
		/// <summary>
		/// SaleAmount : 
		/// </summary>
		private System.Decimal?		  _saleAmount = null;
		
		/// <summary>
		/// OrderID : 
		/// </summary>
		private System.Int32		  _orderId = (int)0;
		
		/// <summary>
		/// CompanyName : 
		/// </summary>
		private System.String		  _companyName = string.Empty;
		
		/// <summary>
		/// ShippedDate : 
		/// </summary>
		private System.DateTime?		  _shippedDate = null;
		
		/// <summary>
		/// Object that contains data to associate with this object
		/// </summary>
		private object _tag;
		
		/// <summary>
		/// Suppresses Entity Events from Firing, 
		/// useful when loading the entities from the database.
		/// </summary>
	    [NonSerialized] 
		private bool suppressEntityEvents = false;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="SalesTotalsByAmountBase"/> instance.
		///</summary>
		public SalesTotalsByAmountBase()
		{
		}		
		
		///<summary>
		/// Creates a new <see cref="SalesTotalsByAmountBase"/> instance.
		///</summary>
		///<param name="_saleAmount"></param>
		///<param name="_orderId"></param>
		///<param name="_companyName"></param>
		///<param name="_shippedDate"></param>
		public SalesTotalsByAmountBase(System.Decimal? _saleAmount, System.Int32 _orderId, System.String _companyName, System.DateTime? _shippedDate)
		{
			this._saleAmount = _saleAmount;
			this._orderId = _orderId;
			this._companyName = _companyName;
			this._shippedDate = _shippedDate;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="SalesTotalsByAmount"/> instance.
		///</summary>
		///<param name="_saleAmount"></param>
		///<param name="_orderId"></param>
		///<param name="_companyName"></param>
		///<param name="_shippedDate"></param>
		public static SalesTotalsByAmount CreateSalesTotalsByAmount(System.Decimal? _saleAmount, System.Int32 _orderId, System.String _companyName, System.DateTime? _shippedDate)
		{
			SalesTotalsByAmount newSalesTotalsByAmount = new SalesTotalsByAmount();
			newSalesTotalsByAmount.SaleAmount = _saleAmount;
			newSalesTotalsByAmount.OrderId = _orderId;
			newSalesTotalsByAmount.CompanyName = _companyName;
			newSalesTotalsByAmount.ShippedDate = _shippedDate;
			return newSalesTotalsByAmount;
		}
				
		#endregion Constructors
		
		#region Properties	
		/// <summary>
		/// 	Gets or Sets the SaleAmount property. 
		///		
		/// </summary>
		/// <value>This type is money</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0. It is up to the developer
		/// to check the value of IsSaleAmountNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? SaleAmount
		{
			get
			{
				return this._saleAmount; 
			}
			set
			{
				if (_saleAmount == value && SaleAmount != null )
					return;
					
				this._saleAmount = value;
				this._isDirty = true;
				
				OnPropertyChanged("SaleAmount");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the OrderID property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32 OrderId
		{
			get
			{
				return this._orderId; 
			}
			set
			{
				if (_orderId == value)
					return;
					
				this._orderId = value;
				this._isDirty = true;
				
				OnPropertyChanged("OrderId");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the CompanyName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String CompanyName
		{
			get
			{
				return this._companyName; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "CompanyName does not allow null values.");
				if (_companyName == value)
					return;
					
				this._companyName = value;
				this._isDirty = true;
				
				OnPropertyChanged("CompanyName");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the ShippedDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsShippedDateNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.DateTime? ShippedDate
		{
			get
			{
				return this._shippedDate; 
			}
			set
			{
				if (_shippedDate == value && ShippedDate != null )
					return;
					
				this._shippedDate = value;
				this._isDirty = true;
				
				OnPropertyChanged("ShippedDate");
			}
		}
		
		
		/// <summary>
		///     Gets or sets the object that contains supplemental data about this object.
		/// </summary>
		/// <value>Object</value>
		[System.ComponentModel.Bindable(false)]
		[LocalizableAttribute(false)]
		[DescriptionAttribute("Object containing data to be associated with this object")]
		public virtual object Tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if (this._tag == value)
					return;
		
				this._tag = value;
			}
		}
	
		/// <summary>
		/// Determines whether this entity is to suppress events while set to true.
		/// </summary>
		[System.ComponentModel.Bindable(false)]
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public bool SuppressEntityEvents
		{	
			get
			{
				return suppressEntityEvents;
			}
			set
			{
				suppressEntityEvents = value;
			}	
		}

		private bool _isDeleted = false;
		/// <summary>
		/// Gets a value indicating if object has been <see cref="MarkToDelete"/>. ReadOnly.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDeleted
		{
			get { return this._isDeleted; }
		}


		private bool _isDirty = false;
		/// <summary>
		///	Gets a value indicating  if the object has been modified from its original state.
		/// </summary>
		///<value>True if object has been modified from its original state; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDirty
		{
			get { return this._isDirty; }
		}
		

		private bool _isNew = true;
		/// <summary>
		///	Gets a value indicating if the object is new.
		/// </summary>
		///<value>True if objectis new; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsNew
		{
			get { return this._isNew; }
			set { this._isNew = value; }
		}

		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public string ViewName
		{
			get { return "Sales Totals by Amount"; }
		}

		
		#endregion
		
		#region Methods	
		
		/// <summary>
		/// Accepts the changes made to this object by setting each flags to false.
		/// </summary>
		public virtual void AcceptChanges()
		{
			this._isDeleted = false;
			this._isDirty = false;
			this._isNew = false;
			OnPropertyChanged(string.Empty);
		}
		
		
		///<summary>
		///  Revert all changes and restore original values.
		///  Currently not supported.
		///</summary>
		/// <exception cref="NotSupportedException">This method is not currently supported and always throws this exception.</exception>
		public virtual void CancelChanges()
		{
			throw new NotSupportedException("Method currently not Supported.");
		}
		
		///<summary>
		///   Marks entity to be deleted.
		///</summary>
		public virtual void MarkToDelete()
		{
			this._isDeleted = true;
		}
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed SalesTotalsByAmountBase Entity 
		///</summary>
		public virtual SalesTotalsByAmountBase Copy()
		{
			//shallow copy entity
			SalesTotalsByAmount copy = new SalesTotalsByAmount();
				copy.SaleAmount = this.SaleAmount;
				copy.OrderId = this.OrderId;
				copy.CompanyName = this.CompanyName;
				copy.ShippedDate = this.ShippedDate;
			copy.AcceptChanges();
			return (SalesTotalsByAmount)copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Deep Copy of this entity.
		///</summary>
		public object Clone(){
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		#endregion
		
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="SalesTotalsByAmountBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(SalesTotalsByAmountBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="SalesTotalsByAmountBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="SalesTotalsByAmountBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="SalesTotalsByAmountBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(SalesTotalsByAmountBase Object1, SalesTotalsByAmountBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;

			bool equal = true;
			if (Object1.SaleAmount != null && Object2.SaleAmount != null )
			{
				if (Object1.SaleAmount != Object2.SaleAmount)
					equal = false;
			}
			else if (Object1.SaleAmount == null ^ Object1.SaleAmount == null )
			{
				equal = false;
			}
			if (Object1.OrderId != Object2.OrderId)
				equal = false;
			if (Object1.CompanyName != Object2.CompanyName)
				equal = false;
			if (Object1.ShippedDate != null && Object2.ShippedDate != null )
			{
				if (Object1.ShippedDate != Object2.ShippedDate)
					equal = false;
			}
			else if (Object1.ShippedDate == null ^ Object1.ShippedDate == null )
			{
				equal = false;
			}
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
		}
	
		#endregion
		
		#region INotifyPropertyChanged Members
		
		/// <summary>
      /// Event to indicate that a property has changed.
      /// </summary>
		[field:NonSerialized]
		public event PropertyChangedEventHandler PropertyChanged;

		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="propertyName">The name of the property that has changed.</param>
		protected virtual void OnPropertyChanged(string propertyName)
		{ 
			OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
		}
		
		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="e">PropertyChangedEventArgs</param>
		protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
		{
			if (!SuppressEntityEvents)
			{
				if (null != PropertyChanged)
				{
					PropertyChanged(this, e);
				}
			}
		}
		
		#endregion
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="entity">The entity.</param>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public static object GetPropertyValueByName(SalesTotalsByAmount entity, string propertyName)
		{
			switch (propertyName)
			{
				case "SaleAmount":
					return entity.SaleAmount;
				case "OrderId":
					return entity.OrderId;
				case "CompanyName":
					return entity.CompanyName;
				case "ShippedDate":
					return entity.ShippedDate;
			}
			return null;
		}
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public object GetPropertyValueByName(string propertyName)
		{			
			return GetPropertyValueByName(this as SalesTotalsByAmount, propertyName);
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{5}{4}- SaleAmount: {0}{4}- OrderId: {1}{4}- CompanyName: {2}{4}- ShippedDate: {3}{4}", 
				(this.SaleAmount == null) ? string.Empty : this.SaleAmount.ToString(),
			     
				this.OrderId,
				this.CompanyName,
				(this.ShippedDate == null) ? string.Empty : this.ShippedDate.ToString(),
			     
				System.Environment.NewLine, 
				this.GetType());
		}
	
	}//End Class
	
	
	/// <summary>
	/// Enumerate the SalesTotalsByAmount columns.
	/// </summary>
	[Serializable]
	public enum SalesTotalsByAmountColumn
	{
		/// <summary>
		/// SaleAmount : 
		/// </summary>
		[EnumTextValue("SaleAmount")]
		[ColumnEnum("SaleAmount", typeof(System.Decimal), System.Data.DbType.Currency, false, false, true)]
		SaleAmount,
		/// <summary>
		/// OrderID : 
		/// </summary>
		[EnumTextValue("OrderID")]
		[ColumnEnum("OrderID", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		OrderId,
		/// <summary>
		/// CompanyName : 
		/// </summary>
		[EnumTextValue("CompanyName")]
		[ColumnEnum("CompanyName", typeof(System.String), System.Data.DbType.String, false, false, false, 40)]
		CompanyName,
		/// <summary>
		/// ShippedDate : 
		/// </summary>
		[EnumTextValue("ShippedDate")]
		[ColumnEnum("ShippedDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		ShippedDate
	}//End enum

} // end namespace
